# helm-chart/backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
      - name: backend
        image: vvram143/myapp/backend:latest
        ports: [{ containerPort: 3000 }]
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef: { name: db-credentials, key: username }
          - name: DB_PASS
            valueFrom:
              secretKeyRef: { name: db-credentials, key: password }

---   
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
   name: backend
spec:
   scaleTargetRef:
       apiVersion: apps/v1
       kind: Deployment
       app: backend
   minReplicas: 1
   maxReplicas: 10
   targetCPUUtilizationPercentage: 75  